---
abstract: 'pure Perl implementation of parts of Sort::Key::Top'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.015, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sort-Key-Top-PP
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Sort::Key::Top::PP:
    file: lib/Sort/Key/Top/PP.pm
    version: 0.003
requires:
  Exporter::Shiny: 0
  perl: 5.008
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Sort-Key-Top-PP/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Sort-Key-Top-PP
  homepage: https://metacpan.org/release/Sort-Key-Top-PP
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-sort-key-top-pp.git
version: 0.003
